packages:
  - apps/*
  - packages/*

catalog:
  typescript: ^5.9.2

catalogs:
  react19:
    '@types/react': ^19.1.11
    '@types/react-dom': ^19.1.5
    react: 19.1.0
    react-dom: 19.1.0

onlyBuiltDependencies:
  - esbuild
