packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  tailwindcss: ^4.1.12
  '@tailwindcss/postcss': ^4.1.12
  typescript: ^5.9.2

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': ^19.1.11
    '@types/react-dom': ^19.1.5

onlyBuiltDependencies:
  - esbuild

