import "./globals.css";
import type { Metadata } from "next";
import { Geist_Mono, Plus_Jakarta_Sans, Baloo_2 } from "next/font/google";
import { Background } from "../components/Background";
import TopNav from "../components/TopNav";
import OnboardingCookieSetter from "../components/OnboardingCookieSetter";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import ConvexClientProvider from "../../../../components/ConvexClientProvider";

const plusJakarta = Plus_Jakarta_Sans({
	variable: "--font-geist-sans",
	subsets: ["latin"],
	display: "swap",
	fallback: [
		"Zen Kaku Gothic New",
		"Hiragino Kaku Gothic ProN",
		"Yu Gothic",
		"Meiryo",
		"system-ui",
		"sans-serif",
	],
});

const baloo = Baloo_2({
	variable: "--font-display",
	subsets: ["latin"],
	weight: "500",
	display: "swap",
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (

		<html lang="en">
			<head>
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@7.3.2/css/flag-icons.min.css"
				/>
			</head>
			<body
				suppressHydrationWarning
				className={`${plusJakarta.variable} ${geistMono.variable} ${baloo.variable} antialiased`}
			>
				<ConvexAuthNextjsServerProvider>
					<ConvexClientProvider>
						<div className="min-h-screen px-4 max-w-7xl mx-auto">
							<Background />
							<TopNav />
							<OnboardingCookieSetter />
							{children}
						</div>
					</ConvexClientProvider>
				</ConvexAuthNextjsServerProvider>
			</body>
		</html>

	);
}
