import "./globals.css";
import type { Metadata } from "next";
import { Geist_Mono, Plus_Jakarta_Sans, Baloo_2 } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "../../../../components/ConvexClientProvider";
import TopNav from "../components/TopNav";
import { Background } from "../components/Background";

const plusJakarta = Plus_Jakarta_Sans({
	variable: "--font-geist-sans",
	subsets: ["latin"],
	display: "swap",
	fallback: [
		"Zen Kaku Gothic New",
		"Hiragino Kaku Gothic ProN",
		"Yu Gothic",
		"Meiryo",
		"system-ui",
		"sans-serif",
	],
});

const baloo = Baloo_2({
	variable: "--font-display",
	subsets: ["latin"],
	weight: "500",
	display: "swap",
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head />
			<body
				suppressHydrationWarning
				className={`${plusJakarta.variable} ${geistMono.variable} ${baloo.variable} antialiased`}
			>
				<ClerkProvider>
					<ConvexClientProvider>
						<Background />
						<div className="min-h-screen px-4 max-w-7xl mx-auto">
							<TopNav />
							{children}
						</div>
					</ConvexClientProvider>
				</ClerkProvider>
			</body>
		</html>
	);
}
